;; -*- mode: eask; lexical-binding: t -*-

(package "ollama-magit-commit-message"
         "0.1.0"
         "Integrate tavernari/git-commit-message with Magit")

(website-url "https://github.com/that1guycolin/ollama-magit-commit-message")
(keywords "convenience" "docs" "local" "tools")

(package-file "ollama-magit-commit-message.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(files "ollama-magit-commit-message.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")
(depends-on "magit" "4.5.0")
(depends-on "transient" "0.12.0")

(development
 (depends-on "elsa" "0")
 (depends-on "package-lint" "0"))
