;;; ollama-magit-commit-message-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ollama-magit-commit-message.el

(autoload 'ollama-magit-commit-message-generate-commit-message "ollama-magit-commit-message" "\
Generate a commit message with git-gen-commit.  Open the Magit commit editor.

ARGS is the list of transient arguments from
`ollama-magit-commit-message-transient'.  If ARGS contains
\"--model=mini\" or \"--model=pro\", the respective model is used;
otherwise the default (8B) model is used.

The function is non-blocking: git-gen-commit runs as a subprocess and
Emacs remains fully responsive.  The commit editor opens automatically
when the model finishes.

(fn &optional ARGS)" t)
(register-definition-prefixes "ollama-magit-commit-message" '("ollama-magit-commit-message-"))


;;; End of scraped data

(provide 'ollama-magit-commit-message-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ollama-magit-commit-message-autoloads.el ends here
